---
title: "Supervised ML Regression"
author: "Christian Sühl"
output:
  html_document:
    toc: TRUE
    theme: united
---


```{r}
# Standard
library(tidyverse)

# Modeling
library(parsnip)

# Preprocessing & Sampling
library(recipes)
library(rsample)

# Modeling Error Metrics
library(yardstick)

# Plotting Decision Trees
library(rpart.plot)
```

```{r}
# Modeling ----------------------------------------------------------------
bike_orderlines_tbl <- readRDS("bike_orderlines.rds")
glimpse(bike_orderlines_tbl)

model_sales_tbl <- bike_orderlines_tbl %>%
  select(total_price, model, category_2, frame_material) %>%
  
  group_by(model, category_2, frame_material) %>%
  summarise(total_sales = sum(total_price)) %>%
  ungroup() %>%
  
  arrange(desc(total_sales))

model_sales_tbl %>%
  mutate(category_2 = as_factor(category_2) %>% 
           fct_reorder(total_sales, .fun = max) %>% 
           fct_rev()) %>%
  
  ggplot(aes(frame_material, total_sales)) +
  geom_violin() +
  geom_jitter(width = 0.1, alpha = 0.5, color = "#2c3e50") +
  #coord_flip() +
  facet_wrap(~ category_2) +
  scale_y_continuous(labels = scales::dollar_format(scale = 1e-6, suffix = "M", accuracy = 0.1)) +
  tidyquant::theme_tq() +
  labs(
    title = "Total Sales for Each Model",
    x = "Frame Material", y = "Revenue"
  )

bike_features_tbl <- readRDS("bike_features_tbl.rds")
glimpse(bike_features_tbl)
  
  # 2.0 TRAINING & TEST SETS ----
bike_features_tbl <- bike_features_tbl %>% 
  
  mutate(id = row_number()) %>% 
  
  select(id, everything(), -url)
  
```

```{r}
# Create a recipe object
bike_recipe <- recipe(price ~ frame_material + category_2 + model, data = bike_orderlines_tbl) %>% #Predict price from frame_material, category_2 and model
  step_dummy(all_nominal(),-frame_material,-category_2,-model,one_hot = T) %>% #Remove all others
  prep() #Estimate the required parameters
```


```{r}
bike_orderlines_tbl %>% distinct(category_2)

# run both following commands at the same time
set.seed(seed = 1113)
split_obj <- rsample::initial_split(bike_orderlines_tbl, prop   = 0.80, 
                                                       strata = "category_2")

# Check if testing contains all category_2 values
split_obj %>% training() %>% distinct(category_2)
split_obj %>% testing() %>% distinct(category_2)

# Assign training and test data
train_tbl <- training(split_obj)
test_tbl  <- testing(split_obj)

# We have to remove spaces and dashes from the column names
train_tbl <- train_tbl %>% set_names(str_replace_all(names(train_tbl), " |-", "_"))
test_tbl  <- test_tbl  %>% set_names(str_replace_all(names(test_tbl),  " |-", "_"))

train_transformed_tbl <- bake(bike_recipe, new_data = train_tbl) #Create training data set
test_transformed_tbl <- bake(bike_recipe, new_data = test_tbl) #Create testing data set
```

```{r}
model_01_linear_lm_simple <- linear_reg(mode = "regression") %>% #Create linear regression model
    set_engine("lm")
```

```{r}
library(workflows)

#Creating workflow
workflow <- workflow(preprocessor = NULL, spec = NULL) %>% 
  workflows::add_recipe(bike_recipe) %>% #Adding recipe
  workflows::add_model(model_01_linear_lm_simple) #Adding model

fitted_workflow <- fit(workflow, train_transformed_tbl) #Estimate model parameters from training set

metrics <- fitted_workflow %>%
           predict(new_data = test_transformed_tbl) %>% #Predict from test data set
           bind_cols(test_transformed_tbl %>% select(price)) %>%
           yardstick::metrics(truth = price, estimate = .pred) %>% print() #Print yardstick metrics
```

