project:
  type: website
  # output-dir: docs
execute: 
  freeze: auto  # Re-render only when source changes
  cache: true

website:
  title: "MyLabJournal"
  favicon: assets/icons/favicon.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "Journal"
        menu: 
          - text: "01 ML Challenge"
            file: content/01_journal/Chapter_1_Challenge.Rmd
          - text: "02 Supervised ML"
            file: content/01_journal/02_supervised_ML_regression.Rmd
          - text: "03 Automated ML"
            file: content/01_journal/03_automated_maschine_learning_with_H2O.Rmd
          - text: "04 Performance Measures"
            file: content/01_journal/04_performance_measures.Rmd
          - text: "05 Performance Measures"
            file: content/01_journal/05_black_box_models_lime.Rmd
          - text: "06 Performance Measures"
            file: content/01_journal/06_deep_learning_challenge.Rmd
      - text: "Links"
        file: content/03_other/06_links.qmd

format:
  html:
    theme:
      dark: darkly
      light: flatly
    highlight-style: a11y-dark
filters:
   - lightbox
lightbox: auto